[project]
name = "treesimmediateconstituents"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "nltk>=3.9.1",
]

[dependency-groups]
dev = [
    "pytest>=8.4.2",
]
